name: tmovie_workspace
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

workspace:
  - packages/core
  - apps/mobile
  - apps/tv

dev_dependencies:
  melos: ^7.0.0

melos:
  name: tmovie_workspace
  repository: https://github.com/qthien202/tmovie_ft

  scripts:
    analyze:
      run: melos exec -- dart analyze .
      description: Run dart analyze in all packages

    build_runner:
      run: melos exec -- dart run build_runner build --delete-conflicting-outputs
      description: Run build_runner in all packages
      packageFilters:
        dependsOn: build_runner

    test:
      run: melos exec -- flutter test
      description: Run tests in all packages
      packageFilters:
        dirExists: test

    clean:
      run: melos exec -- flutter clean
      description: Clean all packages
