name: media_library
description: Favorites + watch history logic for TMovie apps
publish_to: 'none'
version: 1.0.0

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
